config/routes.rb
Healthchecklist::Application.routes.draw do
  
  resources :illnesses do
    resources :questions
  end
  
  root :to => "illnesses#index"
  

end

app/models/illness.rb
class Illness < ActiveRecord::Base
  attr_accessible :illness
  has_many :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :asked, :question
  belongs_to :illness
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/illnesses_controller.rb
class IllnessesController < ApplicationController
  
  before_filter :get_illness
  before_filter :get_illnesses
  
  def get_illness
    @illness = Illness.find_by_id(params[:id])
  end
  
  def get_illnesses
    @illnesses = Illness.all
  end
  
  def index
    # @illnesses = Illness.all # made unnecessary with the before_filter :get_illnesses call
    # @illness = Illness.find_by_id(params[:id]) # made unnecessary with the before_filter :get_illness call
    @illness = Illness.new # to allow user to create an illness from the illness index
  end
  
  def show
    #@illness  = Illness.find_by_id(params[:id]) # made unnecessary with the before_filter :get_illness call
  end
  
  def new
    @illness = Illness.new
  end
    
  def create
    @illness = Illness.create(params[:illness])
    redirect_to illnesses_path if @illness.save
  end
  
  def destroy
    @illness.destroy
    redirect_to illnesses_path
  end
 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  before_filter :get_illness
  
  def get_illness
    @illness = Illness.find(params[:illness_id]) #illness_id because that's the name of the attribute in the questions model
  end
  
  def index
    @questions = @illness.questions
    # @question = @illness.questions.create(params[:question])
  end
  
  def show
    @question = @illness.questions.find(params[:id]) #id here is the id of the question since we're in the question controller
  end
  
  def new
    @question = @illness.questions.new
  end
  
  def create
    @question = @illness.questions.create(params[:question])
  end
  
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to illness_questions_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/illnesses_helper.rb
module IllnessesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/illnesses/create.html.erb
Thanks for adding a new illness.

<%= link_to 'Click here to go back to the list of illnesses', illnesses_path %>
<%= link_to 'Click here to start adding questions for this illness', new_illness_question_path(@illness) %> <% # @illness works because you just created the new illness and assigned it to @illness so we're now passing in the right parameter %>

app/views/illnesses/index.html.erb
<% provide(:title, 'Illnesses') %>
There are <%= @illnesses.count %> illnesses.  Which illness are you visiting your doctor for?  We're currently tracking <%= @illnesses.count %> illnesses.

<% @illnesses.each do |illness| %>
	<ul><%= link_to illness.illness, illness_path(illness) %> (<%= illness.questions.count %> <%= link_to 'questions', illness_questions_path(illness) %> ) <%= link_to 'Delete Illness', illness, :method => :delete %> <%= link_to 'Add Question', new_illness_question_path(illness) %></ul>
<% end %>


<%= form_for(@illness) do |f| %>
	<%= f.text_field :illness %>
	<%= f.submit "Add Illness" %>
<% end %>

app/views/illnesses/new.html.erb
<% provide(:title, 'Add an Illness') %>
<%= form_for(@illness) do |f| %>
<%= f.text_field :illness %>
<%= f.submit %>
<% end %>

app/views/illnesses/show.html.erb
<% provide(:title, 'Individual Illness') %>
<%= @illness.illness %>
<%= link_to 'Questions', illness_questions_path(@illness) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Health Checklist | <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/create.html.erb
Thanks for adding a question!
</br>
<%= link_to 'Go back to illness questions', illness_questions_path %>

app/views/questions/index.html.erb
<% provide(:title, 'Questions' ) %>
These are all <%= @questions.count %> questions for <%= @illness.illness %>: 

<% @questions.each do |question| %>
	<ul><%= question.question %> (<%= question.asked %>) <%= link_to "Delete question", [@illness, question], :method => :delete %></ul>
<% end %>	

<%= link_to 'Add a question', new_illness_question_path(@illness) %>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<%= form_for([@illness, @question]) do |f| %>
	<%= f.text_field :question %>
	<%= f.submit "Add Question" %>
<% end %>

app/views/questions/show.html.erb
<h1>Questions#show</h1>

You are now looking at a question for illness: <%= @illness.illness %>
</br>
<%= @question.question %>